name: Push and Pull Branch

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout wishlist
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Pull changes
      run: git pull origin ${{ github.ref }}

    - name: Push changes
      run: |
        # Make your changes here (e.g., modify files, commit changes)
        git add .
        git commit -m "Automated commit"
        git push origin ${{ github.ref }}
